services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      MongoDb__ConnectionString: mongodb://mongo:27017
      MongoDb__DatabaseName: enterprise_media_vault
      MongoDb__GridFsBucketName: vault_files
      Jwt__Secret: CHANGE_ME_very_secure_key_minimum_32_characters
    depends_on:
      - mongo
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
