<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MongoDB.Driver" Version="2.30.0" />
    <PackageReference Include="MongoDB.Driver.GridFS" Version="2.30.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.0" />
    <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\EnterpriseMediaVault.Application\EnterpriseMediaVault.Application.csproj" />
    <ProjectReference Include="..\EnterpriseMediaVault.Domain\EnterpriseMediaVault.Domain.csproj" />
  </ItemGroup>
</Project>


